# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [2]:
import numpy 

#### Q2 : Afficher la version de numpy et la configuration 

In [3]:
numpy.version.version
numpy.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_info:
  NOT AVAILABLE
blas_src_info:
  NOT AVAILABLE
blas_opt_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
flame_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_info:
  NOT AVAILABLE
lapack_src_info:
  NOT AVAILABLE
lapack_opt_info:
  NOT AVAILABLE
numpy_linalg_lapack_lite:
    language = c
    define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]


#### Q3 : Créer un vecteur nul de taille 10

In [5]:
x = numpy.array([0 for i in range(10)])
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [7]:
y = numpy.array([0 for i in range(10)])
y[4]=1
y

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [9]:
Z = numpy.arange(start=10,stop=50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [12]:
numpy.flip(Z)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [16]:
mat = numpy.arange(9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q8 : Créer une matrice identié 3x3 

In [17]:
I = numpy.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [22]:
R = numpy.random.random((3,3,3))
R

array([[[0.6933697 , 0.73267693, 0.19538533],
        [0.55736792, 0.33242256, 0.29848649],
        [0.51978331, 0.50955836, 0.71774589]],

       [[0.37581318, 0.99759012, 0.73364303],
        [0.78613768, 0.40490982, 0.89339811],
        [0.3528655 , 0.96991825, 0.43906085]],

       [[0.15065706, 0.87908251, 0.17461842],
        [0.12802381, 0.93848949, 0.44682728],
        [0.78598424, 0.64085403, 0.07065146]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [26]:
mr = numpy.random.random((10,10))
print(mr)
minmr = mr.min()
print(minmr)
maxmr = mr.max()
print(maxmr)

[[0.10396729 0.87872051 0.78252433 0.11008947 0.41023584 0.36685624
  0.92416362 0.63499376 0.75235824 0.37743177]
 [0.59763997 0.16642714 0.81293789 0.18260337 0.69639327 0.13440813
  0.93444317 0.3365756  0.16849197 0.40822834]
 [0.87318666 0.27556889 0.2213513  0.51313473 0.70209484 0.16489851
  0.03308613 0.71001558 0.83461454 0.8331499 ]
 [0.97152789 0.9495713  0.80541797 0.47487151 0.71517116 0.15500044
  0.41084993 0.99536237 0.22345213 0.57606845]
 [0.86140943 0.75477571 0.06354882 0.8236169  0.40134714 0.65353499
  0.00951859 0.44855214 0.78666549 0.94945134]
 [0.39210411 0.84259061 0.24185888 0.45233283 0.95977851 0.28467986
  0.52803646 0.07403433 0.13527851 0.64678782]
 [0.18405659 0.20622981 0.84032287 0.18590019 0.63184847 0.17565967
  0.53190802 0.66246661 0.56962028 0.61102948]
 [0.57446471 0.10612034 0.46917898 0.06004379 0.91179933 0.81595269
  0.78974628 0.37670289 0.48846806 0.02757088]
 [0.41059961 0.34694412 0.5468994  0.00989475 0.85240889 0.89718036
  0.56968467

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)